spring.application.name=abatayo

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.asgqpleynqepvviditua
spring.datasource.password=p2bljISbUe4YkFRo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=sb_secret_Q2XFlNi6rOViJMgq01342Q_wfkQWwx4
app.jwt.expiration=3600000 